# Sorting Numpy Array

In [3]:
import numpy as np

np1 = np.array([6,7,4,9,5,3,1,2,8,12,10,11])

#### Sorting 1-D array

**Numerically:**

In [4]:
np.sort(np1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Aplhabetically:**

In [5]:
np2 = np.array(["A","D","V","R","Q","M"])

np.sort(np2)

array(['A', 'D', 'M', 'Q', 'R', 'V'], dtype='<U1')

**Booleans T/F:**

In [6]:
np3 = np.array([True,False,False,True])

np.sort(np3)

array([False, False,  True,  True])

**The Sort uses Copy of Numpy Array not A Numpy View**

### Sorting 2-D array

In [7]:
np2 = np1.reshape(3,4)

np2

array([[ 6,  7,  4,  9],
       [ 5,  3,  1,  2],
       [ 8, 12, 10, 11]])

In [9]:
np.sort(np2)

array([[ 4,  6,  7,  9],
       [ 1,  2,  3,  5],
       [ 8, 10, 11, 12]])

**In 2-D array the sorting is done only rowise**