## Numpy Universal Functions

In [1]:
import numpy as np

In [2]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])

np1

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

**1. Square Root :**

In [4]:
np.sqrt(np1[4:])

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

**2. Absolute Value :**

In [5]:
# Converts negative value into Positive
np.absolute(np1)

array([3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**3. Exponential Value :**

In [6]:
np.exp(np1)

array([4.97870684e-02, 1.35335283e-01, 3.67879441e-01, 1.00000000e+00,
       2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**4. Min/Max Value :**

In [7]:
np.min(np1)

-3

In [8]:
np.max(np1)

9

**5. Sign Negative Or Positive :**

In [9]:
# puts -1 in place of negative values and 1 in place of positiv value
np.sign(np1)

array([-1, -1, -1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1])

**6. Trignomatric functions**

In [10]:
#sin :
np.sin(np1)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849])

In [11]:
#cos:
np.cos(np1)

array([-0.9899925 , -0.41614684,  0.54030231,  1.        ,  0.54030231,
       -0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029,
        0.75390225, -0.14550003, -0.91113026])

In [14]:
#log:
np.log(np1[4:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])