# Slicing Numpy Arrays

In [1]:
import numpy as np

In [2]:
np1 = np.array([1,2,3,4,5,6,7,8,9])

**Slicing and Returning The 2,3,4,5**

In [3]:
np1[1:5]

array([2, 3, 4, 5])

**Slicing Till the end of the array**

In [4]:
np1[3:]

array([4, 5, 6, 7, 8, 9])

**Returning Negative Slices**

In [5]:
# returning 7,8
print(np1[-3:-1])

[7 8]


In [6]:
#steps: by the gap of certain value

print(np1[1:5])
print(np1[1:5:2])# 2-5 in steeps of 2

#steps on the entire array
print(np1[::2])
print(np1[::3])



[2 3 4 5]
[2 4]
[1 3 5 7 9]
[1 4 7]


#### Slicing in 2-D Array

In [7]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# printing the single item: 8
np2[1,2]

8

**Slicing a 2-D Array**

In [8]:
#printing 3,4,5
print(np2[0:1,2:5])

[[3 4 5]]


In [9]:
#printing from both the rows
print(np2[0:2,2:5])

[[ 3  4  5]
 [ 8  9 10]]
