# Shape and Reshape in Numpy Array

**Create 1-D Numpy Array And Get Shape**

In [2]:
import numpy as np

np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

np1.shape

(12,)

**Create 2-D Numpy Array and Get Shape**

In [5]:
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])#2 rows,6cols

np2.shape

(2, 6)

#### Reshape Array

In [6]:
np3 = np1.reshape(3,4) #Reshaping 12 cols into 3 rows and 4 cols

np3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
#Reshapin 2-D array into 3-D array
np4=np2.reshape(2,3,2)

np4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

**Flatten a numpy array**

In [9]:
np5=np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
