# Searching element in the Numpy array

In [1]:
import numpy as np

In [2]:
np1=np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
x = np.where(np1 == 3)
x

(array([2], dtype=int64),)

In [5]:
x[0]

array([2], dtype=int64)

In [7]:
x[0]

array([2], dtype=int64)

In [8]:
np1[x]

array([3])

In [12]:
y = np.where(np1%2==0)

In [13]:
y[0]

array([1, 3, 5, 7, 9], dtype=int64)

In [14]:
np1[y[0]]

array([ 2,  4,  6,  8, 10])

In [18]:
filtered = np1 % 2 ==1
print(filtered)
print(np1[filtered])

[ True False  True False  True False  True False  True False]
[1 3 5 7 9]
