# ***Numpy***

In [1]:
import numpy as np

In [2]:
#creating an simple array with the data type int64
myarr = np.array([[3,6,32,7]], np.int64)
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [3]:
#Accessing the array element
myarr[0,1]

6

In [4]:
#To learn structure of array we can use
myarr.shape

(1, 4)

In [5]:
#To print the type of the data
myarr.dtype

dtype('int64')

In [6]:
#Assigning the value to the specified index
myarr[0,1]=45

myarr

array([[ 3, 45, 32,  7]], dtype=int64)

### Array Creation Methods

#### 1. Conversion from other Python Structures :

           -> Creating an array using python's list or tuples

In [7]:
#using List
listarr = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [8]:
#To get the type of Data
listarr.dtype

dtype('int32')

In [9]:
#To know the Structure of Array
listarr.shape

(3, 3)

In [10]:
#To get the total size of the Array
listarr.size

9

In [11]:
np.array({34,23,22})
#Object types are mainly avoided for performing the any numericals!

array({34, 22, 23}, dtype=object)

#### 2. Intrinsic numpy array creation Objects:
            -> Numpy functions for creating the array (e.g., arange,ones,zeros,etc.)

**1.   Zeros :**

In [12]:
#It is used to create an array of 2 Rows and 5 Columns with Zero as Values
zeros = np.zeros((2,5))

zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**2. ARange :**

In [13]:
#It is used to create an array by the given range
rng = np.arange(15) # creates an array of range 15

rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**3. Linspace :**

In [14]:
#It is used to equally spaced {divide} the range in the given input obj.linspace(from,To,Number of Parts to be devide)
lspace = np.linspace(1,50,10) #dividing the range 1 to 5 in 12 equal parts!

lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**4. Empty :**

In [15]:
#It creates an array with totally random array values
emp = np.empty((4,6))

emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56597770e-307, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

**5. Empty_Like :**

In [16]:
#It creates an empty array by using an already created array
emp_like = np.empty_like(lspace)
#we can modify thevalues as we like!
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**6. Identity :**

In [17]:
#It creates an identity matrix of given N
ide = np.identity(3)

ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**7. Full :**

In [18]:
#It creates an array with the fixed value for all the range

#single Dimensional
np1 = np.full((10),6)

np1


array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [19]:
#Multi Dimensional
np2 = np.full((5,4),7)

np2

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])